version: "3"

services:
  mc-paper-server:
    build:
      context: ./test_server
      args:
        - memory_size=4G
    volumes:
      - ./test_server:/data:rw
    ports:
      - "25565:25565"
    environment:
      - MEMORYSIZE=4G
    restart: unless-stopped
